source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def import_pods
    pod 'ASCIIfy', :path => '../'
end


target 'ASCIIfy_iOS_Example' do
    platform :ios, '12.0'
    import_pods
    target 'ASCIIfy_iOS_Tests' do
        inherit! :search_paths
    end
end

target 'ASCIIfy_OSX_Example' do
    platform :osx, '10.11'
    import_pods
    target 'ASCIIfy_OSX_Tests' do
        inherit! :search_paths
    end
end

# --- POST INSTALL ACTIONS ------
post_install do |installer|
  # This removes the warning about swift conversion, hopefuly forever!
  installer.pods_project.root_object.attributes['LastSwiftMigration'] = 9999
  installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
  installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999

  shared_data_dir = Xcodeproj::XCScheme.user_data_dir(installer.pods_project.path)
  Dir["#{shared_data_dir}/*.xcscheme"].each do |scheme_path|
    scheme = Xcodeproj::XCScheme.new scheme_path
    scheme.doc.root.attributes['LastUpgradeVersion'] = 9999
    scheme.save!
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
